### PR TITLE
Swipe with transition

### PR DESCRIPTION
**Pull request by jkettmann**

### CODE REVIEW

**Comment by jossmac** [comment]
Thanks @jkettmann

Could you please update or resubmit without the `/dist` and `/lib` files?

**Comment by jkettmann** [comment]
@jossmac Great to get this going again. Is it ok like this?

**Comment by jossmac** [comment]
@jkettmann no, sorry mate, this will delete the files from the repo. The  PR should only include changes to `/src` and `/examples/src`.

**Comment by jkettmann** [comment]
@jossmac Yeah sorry. A bit to early in the morning :-). Just to be clear: I'll revert all changes  for dist and lib directories to the last commit before I started developing. Then I'll commit. That should do it right? I also added some dependencies to package.json. These should also be included, right?

**Comment by jossmac** [comment]
@jkettmann that'd be great, thank you!

**Pull request merged**
