### PR TITLE
Add onClickImage prop

### PR DESCRIPTION
**Pull request by pradel**
Added an onClickImage prop to lightbox with the associated doc.
I also updated the example (when a user click on the last image of the lightbox it will close it).

### CODE REVIEW

**Comment by pradel** [comment]
With this prop you can handle more things like restart the slideshow after last image, close the slider etc ..

**Comment by jossmac** [comment]
Thanks for the PR @pradel 

This change conflicts with `onClickShowNextImage` from https://github.com/jossmac/react-images/blob/master/src/Lightbox.js#L91

Perhaps you could merge the two?

**Comment by pradel** [comment]
@jossmac `onClickShowNextImage` is not documented yet should I remove this prop? What do you mean by merging the two?

**Comment by pradel** [comment]
@jossmac ?

**Pull request merged**
