### PR TITLE
Feature/customization

### PR DESCRIPTION
**Pull request by wyqydsyq**
Allows users of the library to specify custom styles and a custom render method for image details via `props`

**Description of changes:**
- Add `imageStyle` option to style `img` tag
- Add `containerStyle` option to style `figure` tag
- Add `Details` option to override default `Footer` component

**Checks:**

- [x] Please confirm `npm run lint` ran successfully
- [x] Please confirm that only `/src` and `/examples/src` are committed
- [x] [if new feature] Please confirm that documentation was added to the README.md

### CODE REVIEW

**Comment by benhowell** [comment]
I wonder if these changes would be better off as a part of the `theme` prop?

**Comment by wyqydsyq** [comment]
`theme` prop isn't documented, I was under the impression it was intended for internal use or in conjunction with a third party theme provider service. Regardless, explicit properties is far more discoverable (being easier to document and a more standard way to do it) to end users than an ambiguous object.

**Comment by jossmac** [comment]
@wyqydsyq @benhowell `theme` needs more thought to be truly useful; sorry about that.

@wyqydsyq Looks good to me, just a few things of note:
- there's an unused module `require-dir` in the package.json
- In the [README.md update](https://github.com/jossmac/react-images/pull/145/files#diff-04c6e90faac2675aa89e2176d2eec7d8R130) there's a reference to a non-existent method `this.renderDetails` - please fix, consumers take these examples literally.
- please add `containerStyle` and `imageStyle` to Lightbox `propTypes`
- I don't love the capitalised prop `Details`, how about `renderFooter`?

**Comment by wyqydsyq** [comment]
Hey guys, I'm no longer using this library (ended up rolling our own solution) so don't really need this myself any more. If anyone else wants to address the changes requested above and submit a new PR, feel free to fork from my branch this PR is based on: https://github.com/Codafication/react-images/tree/feature/customization

**Pull request closed without merging**
