### PR TITLE
fixes #26 scrollbar disappearing in IE after closing lightbox

### LINKED ISSUE #26: Disappearing scrollbar on lightbox show
If a page has scrollbar image
it disappears on lightbox show 
image

Also, in IE, when we close lightbox - scrollbar doesn't appear

### PR DESCRIPTION
**Pull request by neptunian**

### CODE REVIEW

**Comment by jossmac** [comment]
@neptunian after thinking about this for a while, I wonder if we need to kill `overflow` at all. Do you care if the user scrolls the body behind the gallery?

**Comment by neptunian** [comment]
Nope, the ability to scroll does not seem to detract from the user experience.

**Comment by jossmac** [comment]
We'll find a better solution for this in the future. I'm not comfortable leaving styles in the consumer's DOM once our component has unmounted

**Comment by neptunian** [comment]
@jossmac  good point...

**Pull request closed without merging**
