### PR TITLE
[DO NOT MERGE] V1 all the things

### PR DESCRIPTION
**Pull request by jossmac**
### 🎉 [v1 Demo -->](http://bit.ly/react-images-v1)

* * *

Alpha releases of `react-images@1.0.0-alpha.x` available on npm:

```bash
yarn add react-images@next
```

### Still left to do:

**Core**
- [x] settle on and implement a build tool
  - [rollup](https://rollupjs.org/)
- [ ] unit tests for each component
- [x] lockdown the API and release an alpha
- [x] light-weight theming/styling for components
  - the `styles` property accepts an object of component keys
- [x] add classnames for those who prefer styling with CSS
- [ ] pagination component
- [x] implement ARIA best practices on default components

**Docs**
- [x] standalone carousel
- [x] modal carousel
- [x] carousel synchronised with url
- [x] custom components
- [x] custom styles
- [ ] simple examples for CodeSandbox

### CODE REVIEW

**Comment by raiprabh** [comment]
Hey guys, can you let me know how do you build this branch? I tried `yarn build`, but got a number of errors. Here are the ones:

```
[build.rollup] [!] Error: 'components' is not exported by src/components/defaultComponents.js
[build.rollup] https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
[build.rollup] src/index.js (6:9)
[build.rollup] 4: import { default as ModalGateway } from './components/Modal/Gateway';
[build.rollup] 5: import { default as Modal } from './components/Modal/Modal';
[build.rollup] 6: import { components } from './components/defaultComponents';
[build.rollup]             ^
[build.rollup] 7:
[build.rollup] 8: export default Carousel;
```

I fixed the above one by changing the index.js file to 

```
// @flow

import Carousel from './components/Carousel';
import { default as ModalGateway } from './components/Modal/Gateway';
import { default as Modal } from './components/Modal/Modal';
import { carouselComponents, modalComponents, defaultCarouselComponents, defaultModalComponents } from './components/defaultComponents';

export default Carousel;
export { Modal, ModalGateway };
export { carouselComponents, modalComponents, defaultCarouselComponents, defaultModalComponents };
```

and index.umd.js file to

```
// This file exists as an entry point for bundling our umd builds.
// Both in rollup and in webpack, umd builds built from es6 modules are not
// compatible with mixed imports (which exist in index.js)
// This file does away with named imports in favor of a single export default.

import Carousel from './components/Carousel';
import { default as ModalGateway } from './components/Modal/Gateway';
import { default as Modal } from './components/Modal/Modal';
import { carouselComponents } from './components/defaultComponents';

Carousel.components = carouselComponents;
Carousel.Modal = Modal;
Carousel.ModalGateway = ModalGateway;

export default Carousel;
```

Since the line `import { components } from './components/defaultComponents';` errors out as `components` is not exported.

Even after doing this, the next error while building is:

```
[build.rollup] [!] Error: 'ViewPager' is not exported by node_modules/react-view-pager/lib/react-view-pager.js
[build.rollup] https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
[build.rollup] src/components/Carousel.js (7:9)
[build.rollup] 5: import glam from 'glam';
[build.rollup] 6: import rafScheduler from 'raf-schd';
[build.rollup] 7: import { ViewPager, Frame, Track, View as PageView } from 'react-view-pager';
[build.rollup]             ^
[build.rollup] 8:
[build.rollup] 9: const viewPagerStyles = { flex: '1 1 auto', position: 'relative' };
[build.rollup]
```

For this I have no clue, have tried changing the version for `react-view-pager`. Can anyone share the build with me?

**Comment by slorenzo** [comment]
Ey! I really like the alpha version of this project!

When will it be stable? Hope soon!

**Comment by borisrorsvort** [comment]
@neptunian is this still maintained / worked on?

**Comment by neptunian** [comment]
@borisrorsvort We've been a bit busy but I'd like to think so. I plan to spend some time on it and hopefully @jossmac will have some time!

**Comment by guillaumebriday** [comment]
Hey 👋  Any update on this PR ? Thank you for your work !

**Comment by guillaumebriday** [comment]
Yeahhhh 👍🎉🎊

Thank you @neptunian

**Pull request merged**
