### PR TITLE
Remove generated code from repo & remove images in npm repo

### LINKED ISSUE #40: Example images are included in npm repo
```
$ du -hs node_modules/react-images/*
...
6.5M	node_modules/react-images/examples
```

Probably don't need to download 6 megs of cute animal photos on every deploy. Add a `.npmignore` file to remove the examples folder. [docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).

### PR DESCRIPTION
**Pull request by pradel**
- Remove the lib folder since it's not necessary in the repo
- Added a prepublish task to force build before publishing a new version 
- Removing examples from npm repo close #40

### CODE REVIEW

**Comment by JedWatson** [comment]
@jossmac this looks good to me

**Comment by neptunian** [comment]
There is a reference to the lib directory in package.json:
"main": "lib/Lightbox.js"

Also react-images uses react-component-gulp-tasks module which by default adds lib tasks
https://github.com/JedWatson/react-component-gulp-tasks/blob/master/index.js

Why is there the lib and dist directory?  Is it necessary to have both?  @JedWatson

**Comment by jossmac** [comment]
Sorry I didn't get to this sooner, I've been busy and this repo has suffered for it.

Whilst I'm good at UI/UX, I'm not confident with build processes and used `react-component-gulp-tasks` because it was an out-of-the-box solution.

@pradel If you have a tidier solution I would love your help. Would you be open to that?

**Comment by pradel** [comment]
I am on holiday for a few days but when I come back I will work on that :smile:

**Comment by GregoryPotdevin** [comment]
Guess I missed this discussion.

For my projects I use [nwb](https://github.com/insin/nwb) which seems to generate a pretty clean projet and npm publish. It used to be stuck with Babel 5 but got updated 4 days ago and now defaults to Babel 6.

It's kind of like `create-react-app` but it has multiple project types, and I use `nwb new react-component`. It gives you the src folder, webpack+babel with hot reloading, unit tests, and a documentation folder. A bit slow to install as it installs phantomjs for the tests.

Might do a quick test today I guess ^^

**Comment by GregoryPotdevin** [comment]
Here's a fork which uses `nwb` : https://github.com/GregoryPotdevin/react-images/tree/nwb-build

The main issues I ran into : 
- nwb has it's own template for the demo's index.html, so all the HTML needs to be in react. Not perfect but works well
- not sure why but the umd bundle was including all of React. I had to declare `react-addons-css-transition-group` as 'external' to prevent Webpack from pulling in React

Apart from that, the demo works fine, with hot reloading. The tests are ready to use (but I haven't added any yet). The npm package is really clean, only the required files are sent (lib, es, and umd folders).

**Comment by pradel** [comment]
outdated pr :)

**Pull request closed without merging**
