### PR TITLE
Feature/rich text figcaption

### PR DESCRIPTION
**Pull request by duyenho**
**Description of changes:**
- Installed html-react-parser to parse html strings as photo captions
- In the Footer component, I wrapped the caption prop in a Parser function
- Added a `<br>` tag to test in the Default Options Gallery
- Not sure if I'm supposed to commit the package.lock.json - you might want to do that if necessary

**Related issues (if any):**
n/a

**Checks:**

- [x] Please confirm `yarn run lint` ran successfully
- [x] Please confirm that only `/src` and `/examples/src` are committed
- [x] [if new feature] Please confirm that documentation was added to the README.md

### CODE REVIEW

**Comment by duyenho** [comment]
Hi Joss,
Thanks for your library.
Hope the feature is helpful.
Cheers,
Duyen

**Comment by micahstubbs** [comment]
👍 for this PR.  I'd like to have this feature too 😄 

let's see why the CI build fails

```
2:38:08 AM: Failing build: Failed to build site
2:38:08 AM: failed during stage 'building site': Deploy directory 'docs/dist' does not exist
```
netlify logs https://app.netlify.com/sites/react-images/deploys/5a9a7acc295b5522f406081c

**Comment by micahstubbs** [comment]
just checked this branch out and ran `yarn start` to open the examples page at http://localhost:8000

✅ from me

react-images-html-1

@jossmac would be cool to merge this one soon 😄

**Comment by 3stacks** [comment]
Really keen to get this feature in!

**Comment by davwheat** [comment]
Looks like this got overlooked for a long time! Let's add it.

**Pull request closed without merging**
