### PR TITLE
Update documentation and example for yarn

### PR DESCRIPTION
**Pull request by jorrit**
**Description of changes:**

Changes some docs to clarify that yarn is the preferred package manager for this project. Removes package-lock.json.

**Related issues (if any):**

**Checks:**

- [x] Please confirm `npm run lint` ran successfully
- [x] Please confirm that only `/src` and `/examples/src` are committed
- [x] [if new feature] Please confirm that documentation was added to the README.md

### CODE REVIEW

**Comment by rickerd** [comment]
Done in my PR https://github.com/jossmac/react-images/pull/196

**Comment by neptunian** [comment]
@jorrit  can you fix the conflict and i'll merge?  thanks.

**Comment by jorrit** [comment]
@neptunian done

**Comment by jorrit** [comment]
👍

**Pull request merged**
