### PR TITLE
Srcset support related

### PR DESCRIPTION
**Pull request by neptunian**
These are some changes before committing srcset support.
A few things:

-Unfortunately I could not find a single image placeholder generator site that provided multiple sizes, including square thumbnail sizes of the same image in order to have several sizes for srcset support examples (including the http://lorempixel.com/ site i mentioned).  The easiest thing I found was to just use Flickr which provides several common sizes for any image including small thumbs.  I own the copyright to all these images and they are free to use.

-Separate out thumbnail images from larger Lightbox images into its own array.  Eventually I think the array can be an array of objects with srcset and thumbnail items.

-Darken the backdrop to the Lightbox.  Found the background to be a bit distracting being so light previously.

### CODE REVIEW

**Comment by jossmac** [comment]
@neptunian thanks for the PR, a few things:

- first of all thank you for lending your images to this project, I'm very grateful
- separate array for thumbnails is great, though would you mind renaming the property `thumbnails` (rather than `thumbs`)?
- backdrop opacity is cool

Lastly, and maybe I'm missing something, I can't see `srcset` in this PR

**Comment by neptunian** [comment]
Yeap, will do.  I thought, just to be clear, I'd push this first, then the srcset.  But you can wait for that commit if you want.  (i was reading the pull request etiquette and thought I should make each change into a pull request :P )

**Comment by neptunian** [comment]
@jossmac I've added srcset support in commit 625cc43.  I haven't updated the docs yet.  I am hoping you can have a look and let me know what you think.

**Comment by jossmac** [comment]
This is terrific, thank you for your work @neptunian

**Pull request merged**
