### PR TITLE
Not all properties in custom 'theme' object are used

### PR DESCRIPTION
**Pull request by clintharris**
You currently aren't able to customize all theme properties. For example, passing in `<Lightbox theme={myTheme} .../>` where `myTheme.footer.height = 200` doesn't do anything. This appears to be happening because methods in `Lightbox.js` are referencing the `theme` module as it is imported from `./theme.js` and ignoring `this.props.theme`.

**Description of changes:**
- `src/Lightbox.js`: Modified to do `deepMerge()` of `this.props.theme` with the default theme in `theme.js`. Changed references from the `import`ed `theme` module to use `this.theme` instead.

- `examples/src/app.js`: Modified to show that add'l theme props can be used (e.g., `theme.footer.height`)

**Checks:**

- [x] Please confirm `npm run lint` ran successfully
- [x] Please confirm that only `/src` and `/examples/src` are committed
- [ ] [if new feature] Please confirm that documentation was added to the README.md

### CODE REVIEW

**Comment by jossmac** [comment]
Thanks @clintharris!

Please remove the `dist` and `examples/dist` files, then this is good to merge

**Comment by jossmac** [comment]
@clintharris `dist/*` is created as part of the build process

**Comment by clintharris** [comment]
Hey @jossmac, changes to `example/dist/*` have been removed

**Comment by neptunian** [comment]
@clintharris your changes broke the demo where the close button on all the modals were no longer visible and the themed demo with thumbnails image no longer showed up.  please check your work next time. i am fixing the issues.

**Pull request merged**
