### PR TITLE
Swipe with transition

### PR DESCRIPTION
**Pull request by jkettmann**
Continuing (#110)[https://github.com/jossmac/react-images/pull/110] here. Separated swipe feature from full screen feature.

### CODE REVIEW

**Comment by neptunian** [comment]
hey @jkettmann little confused because it seems @jossmac created a branch on the same day: https://github.com/jossmac/react-images/tree/feature/swipe ?

**Comment by jkettmann** [comment]
Hi @neptunian, I have no idea about the new branch, but it seems to be a different and quite short implementation of swiping. I just pushed my implementation of swipe without the fullscreen feature. If @jossmac implementation is working fine, we might consider it over mine, because mine is rather complicated.

**Comment by neptunian** [comment]
let's see if @jossmac  will have some time to comment on his intention.

**Comment by littletower** [comment]
any new on when this might be available? thx

**Comment by jossmac** [comment]
@jkettmann @neptunian @littletower i'm really sorry i've left this for so long.

Touch and fullscreen support will be available in v1 (#199) which is a complete rewrite of the library. I'd like to invite you to [review the branch](https://github.com/jossmac/react-images/tree/v1) and let me know what you think of the direction I've taken.

* * *

Closing this PR for now, please comment if you'd like it reopened.

**Pull request closed without merging**
