### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by fend25**
Fixed react-addons-transition-group version requirement from ^15.0 (which resolves to react@15.2 and crashes some other deps) to ^15.0.0 which will resolve to 15.0.2 actually.

### CODE REVIEW

**Comment by jossmac** [comment]
Thanks @fend25!

**Comment by fend25** [comment]
@jossmac thank you very much! please push new release to the npm ASAP.

**Comment by jossmac** [comment]
v0.4.7 🎉

**Comment by neptunian** [comment]
@fend25  did this work for you?  I'm having the same issue though it could be my version of JSPM (vs using npm).

```
"npm:react-images@0.4.7": {
      "jss": "npm:jss@3.11.1",
      "jss-camel-case": "npm:jss-camel-case@1.1.0",
      "jss-nested": "npm:jss-nested@1.0.3",
      "jss-px": "npm:jss-px@1.0.0",
      "jss-vendor-prefixer": "npm:jss-vendor-prefixer@2.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.0.2",
      **"react-addons-transition-group": "npm:react-addons-transition-group@15.2.1",**
      "react-dom": "npm:react-dom@15.0.2",
      "react-jss": "npm:react-jss@2.1.1",
      "react-swipeable": "npm:react-swipeable@3.5.1"
    },

    "npm:react-addons-transition-group@15.2.1": {
      "react": "npm:react@15.2.1"
    },
```

It still resolves to react-addons-transition-group@15.2.1 which updates React to 15.2 which breaks my site.  Shouldn't a tilde be used?  Like "react-addons-transition-group": "~15.0.0",

**Pull request merged**
